GET {{BASE_URL}}

GET {{BASE_URL}}/transactions

POST {{BASE_URL}}/auth/signup
Content-Type: application/json

{
    "username": "A14",
    "password": "1234568"
}

POST {{BASE_URL}}/auth/signin
Content-Type: application/json

{
    "username": "A14",
    "password": "1234568"
}
